### ISSUE TITLE
Add option to disable contact photo

### ISSUE THREAD

**Issue by mcheban** [matejdro/PebbleDialer-Android#13]
On some photos text is not readable

**Comment by matejdro** [comment]
Can you take a picture of unreadable text?

**Comment by mcheban** [comment]
![dialer_screen](https://cloud.githubusercontent.com/assets/631809/8373504/3ba7a876-1bf6-11e5-96ed-9fdfb809af7c.jpg)

**Comment by matejdro** [comment]
OK, just wanted to check if it is caused by glitch or something. Will add the option in next version.

**Comment by matejdro** [comment]
Implemented in new version.
