### ISSUE TITLE
No release tags in git repository

### ISSUE THREAD

**Issue by ashimokawa** [matejdro/PebbleDialer-Android#22]
While including [PebbleDialer in f-droid](https://f-droid.org/repository/browse/?fdfilter=pebble&fdid=com.matejdro.pebbledialer) I found that there are absolutely no tags in both PebbleDialer-Android and PebbleAndroidCommon, so I had to guess the correct revisions from the release date of version 2.4

It would be great if you could add the tags for 2.4 or consider to push tags for future releases.

**Comment by matejdro** [comment]
Yeah I do plan to use tags in the future (already using them for Notification Center, although I keep forgetting to push them). Does PebbleAndroidCommons need tags, considering that it is compiled directly?

Even bigger problem than that is that by uploading to F-droid I would have to set up separate branch with removed crashlytics and keep that one updated which is just a lot of hassle IMO.

**Comment by ashimokawa** [comment]
@matejdro
You can push all the forgotten tags at once at any time with git push --tags
Also PebbleAndroidCommons needs tags, else no one can reproduce a specific release later.

About F-Droid: I pushed a metadata + patch which removes crashlytics to F-Droid. Their buildserver already build PebbleDialer and I plan to maintain the crashlytics removal patch, so there is zero hassle for you.
Just the tags would help to have f-droid builds equaling the official build you release to google play.

**Comment by matejdro** [comment]
Can you specify arbitrary tag names in F-Droid build process? Because PebbleAndroidCommons would have its own version system due to being used by both Dialer and NC.

**Comment by ashimokawa** [comment]
@matejdro
Yes I can, and I do, just that the tags are not tags but the full git commit hashes right now ;)
Have a look here:

https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.matejdro.pebbledialer.txt
<pre>
commit=97cfcaeb13f47b341795afea4b4c31134057c7d1
srclibs=AndroidPebbleCommons@9e3017a233a1a1e7d06354e064068c30dcf5288f
</pre>

**Comment by matejdro** [comment]
Well problem is that PebbleAndroidCommons often just has one commit added. Should I just increment  version number every time and add new tag?

**Comment by ashimokawa** [comment]
For PebbleAndroidCommons I dont know about version numbers, if it has tags it would be enough. And yes, if it only has one commit and then is used by either a PebbleDialer or a NotificationCenter release it would need a tag (or two at the same revision if used by both PD and NC, like NC_2.4 and PD_2.6.3).
At least for PebbleDialer tags would be farther away that 1 commit. If for NC there is one tag per commit in PebbleAndroidCommons, so be it. ;)

**Comment by matejdro** [comment]
Just released new version ad added tag to it. I add tags for every version, but feel free to remind me if I ever forget it.

Commons is being versioned by revision numbers now (r1, r2 etc.), PebbleDialer readme states which revision should be used to build last stable release.

**Comment by ashimokawa** [comment]
There are still no tags in this repository
Are you sure you pushed them with git push --tags ?

**Comment by matejdro** [comment]
Right, totally forgot to do that. They are there now.

**Comment by ashimokawa** [comment]
@matejdro 
Confirmed ;)
Thanks!

**Comment by ashimokawa** [comment]
Is 2.42 supposed to build against r1 or r2 of the Commons library?

Because compiling against 2.42 results in
<pre>
:app:compileReleaseJava/home/andi/fdroid/fdroiddata/build/com.matejdro.pebbledialer/app/src/main/java/com/matejdro/pebbledialer/PebbleDialerApplication.java:27: error: method init in class LogWriter cannot be applied to given types;
        LogWriter.init(preferences, "PebbleDialer");
</pre>

Maybe it would be better to tag the commons library with tags like "PD 2.42" and "NC X.XX", if a revision is used for both projects that two tags would be at the same revision.

**Comment by matejdro** [comment]
2.42 is building against r1 as mentioned in 2.42's readme: https://github.com/matejdro/PebbleDialer-Android/blob/2.42/README.md

Naming against NC or PD versions would be a mess, especially if I start more projects that use commons.

**Comment by ashimokawa** [comment]
Ok, sorry, I will rely on the README.md from now on
